### ISSUE TITLE
Projects not found if install path is not https://devopsservername/DefaultCollection

### ISSUE THREAD

**Issue by JaSon-Share** [expertasolutions/VstsDashboard#105] opened 2020-04-08 07:07 UTC
Hello Team,
  we are facing an issue that if the path to DevopsServer Collection is different from https://devopsservername/DefaultCollection the projects are not found(in our case it is https://devopsservername/tfs/DefaultCollection)

![2020-04-08 08_27_18-Window](https://user-images.githubusercontent.com/63337257/78754832-77226280-7978-11ea-9357-2094888ed7e9.png)

On a Dev/Lab system where the path is set as https://labdevopsservername/DefaultCollection the Projects are found correctly.

Can you please check from your end, as the Dashboard would be a really great help for us.

THX and BR,
   Jan

**Comment by lturmel** [comment] 2020-04-08 10:45
> Hello Team,
> we are facing an issue that if the path to DevopsServer Collection is different from https://devopsservername/DefaultCollection the projects are not found(in our case it is https://devopsservername/tfs/DefaultCollection)
> 
> ![2020-04-08 08_27_18-Window](https://user-images.githubusercontent.com/63337257/78754832-77226280-7978-11ea-9357-2094888ed7e9.png)
> 
> On a Dev/Lab system where the path is set as https://labdevopsservername/DefaultCollection the Projects are found correctly.
> 
> Can you please check from your end, as the Dashboard would be a really great help for us.
> 
> THX and BR,
> Jan

Hi @JaSon-Share , it's seems to be cause by another issue, which lead to not being able to get the data from Azure DevOps Server. On the upper left corner of your screenshot I remark the "vundefined" is normally where we found the version number of the current extension, like this:
![CI_CD_Dashboard_-_Pipelines](https://user-images.githubusercontent.com/46848645/78775087-a67aa480-7963-11ea-8796-ad83d16e7251.png)

Just to confirm you that the url with "tfs/defaultCollection" normally works, I've a customer where I work everyday as consultant, have the same configuration as your organization and the extension is working properly.

I've questions for you:
- Which version of Azure DevOps Server is your Dev/Lab System ?
- Which version of Azure DevOps Server is your Production on ?
- Do you have any kind of permission that your user has that can limit the access to Azure DevOps Server ? (Stupid question, but it worth to ask it too :p )

With yours answers, I will try to reproduce your Azure DevOps Server scenario to identity why it's not properly working, before the end of the week.

**Comment by JaSon-Share** [comment] 2020-04-08 11:34
Helleo @lturmel,

  we have DevopsServer 17.143.28511.3 on prod and 17.153.29522.3 on lab/dev, as we use to copy over the prod db to dev and then migrate for testing the account i use has the same rights on both systems (currently owner:-))

yes the difference is just the /tfs/ on prod

THX and BR

**Comment by lturmel** [comment] 2020-04-08 22:00
> Hello @lturmel,
> 
> we have DevopsServer 17.143.28511.3 on prod and 17.153.29522.3 on lab/dev, as we use to copy over the prod db to dev and then migrate for testing the account i use has the same rights on both systems (currently owner:-))
> 
> yes the difference is just the /tfs/ on prod
> 
> THX and BR

Hi @JaSon-Share 

Your DevLab is (**17.153.29522.3**) which is Azure DevOps Server **2019.1.1**
Your Prod is on (**17.143.28511.3**) which is Azure DevOps Server **2019 RC(?)**

So it's also a good difference between 17.143 and 17.153, just look at the link below:
https://docs.microsoft.com/en-us/azure/devops/release-notes/features-timeline#server-build-numbers

I have tested with:
- Azure DevOps Server 2019 RTW (17.143.28621.4) = not working
- Azure DevOps Server 2019.0.1 (17.143.28912.1) = not working
- Azure DevOps Server 2019.1.0 (17.153.29207.5) = Work as expected

From these observations, I've to temporary set a limitation on this extension to only be installable from Azure DevOps Server version minimal to 2019.1.0 (17.153.29207.5).

I will look if can worth the effort to make it works for previous version of Azure DevOps Server, but it will not be something I can address this week.

Thanks for your times

**Comment by lturmel** [comment] 2020-04-09 00:26
I've create the issue #107 to investigate for the possibility to add support for previous Azure DevOps Server version

**Comment by lturmel** [comment] 2020-04-25 13:12
Hi @JaSon-Share from our last exchange, I'm sorry to say that I will it will not be possible to support Azure DevOps Server version lower than 17.153.*. I've put time to evaluate it from the issue #107 and explain it as a release note from the PR #124 that will be in may delivery.

Best regards,

**Closed by lturmel** 2020-04-25 13:12 UTC
Labels: Under Investigation, question
